services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=games
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    ports:
      - 6379:6379

  http:
    build:
      context: .
      dockerfile: "./dockerfiles/http.dockerfile"
    depends_on:
      - postgres
    environment:
      # - DATABASE_URL=postgresql://neondb_owner:npg_Irot0WKhAz8w@ep-divine-haze-amo9rqsk-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/games
      - REDIS_URL=rediss://default:gQAAAAAAAT30AAIncDFlOGMwYTk2MjBlNmU0Nzk5OWI5N2FjNTUyOGNlOGU2N3AxODEzOTY@sharp-kid-81396.upstash.io:6379
      - JWT_SECRET=1001001010AJAJAJJA
    ports:
      - 3000:3001